services:

  nginx:
    container_name: nginx
    build: ./nginx/build/.
    restart: unless-stopped
    ports:
      - 8000:80
    expose:
      - 80 # for synthetics worker
      - 81 # for status checks
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    labels:
      com.datadoghq.ad.check_names: '["nginx"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: '[{"nginx_status_url": "http://nginx:81/nginx_status/"}]'
      com.datadoghq.ad.logs: '[{"source": "nginx", "service": "nginx"}]'
    environment:
      - DD_SERVICE="nginx"
      - DD_ENV
      - DD_VERSION
      - DD_AGENT_HOST=datadog

  flask:
    container_name: flask
    build: flask/build/.
    volumes:
      - ./flask:/flask
      - ../static:/data/static:ro
    extra_hosts:
      - "host.docker.internal:host-gateway" # to access a local ollama server
    environment:
      - DD_SERVICE=flask
      - DD_ENV
      - DD_VERSION
      - DD_CLIENT_TOKEN
      - DD_APPLICATION_ID
      - DD_SITE
      - DD_API_KEY
      - DD_LOGS_ENABLED=true
      - DD_LOGS_INJECTION=true
      - DD_TRACE_ANALYTICS_ENABLED=true
      - DD_LLMOBS_ENABLED=1
      - DD_LLMOBS_ML_APP=ollama
      - DD_AGENT_HOST=datadog
      - DD_TRACE_AGENT_PORT=8126
      - FLASK_SECRET=somesupersecret
      - REDIS_HOST=redis
      - OLLAMA_MODEL # ollama model to use for chat
      - OLLAMA_TEMPERATURE=0.5  # control creativity (0.0-1.0)
      - OLLAMA_TOP_P=0.7  # nucleus sampling parameter
      - OLLAMA_NUM_PREDICT=512  # max number of tokens to generate
      - OLLAMA_NUM_CTX=4096  # context window size
      - OLLAMA_HOST=http://host.docker.internal:11434
    labels:
      com.datadoghq.ad.logs: '[{"source": "python", "service": "flask", "log_processing_rules": [{"type": "multi_line", "name": "log_start_with_date", "pattern" : "\\[?\\d{4}-\\d{2}-\\d{2}"}]}]'
    expose:
      - 8001

    command: ddtrace-run gunicorn -w 2 -b :8001 --timeout 60 wsgi:app


  redis:
    container_name: redis
    image: "redis"
    expose:
      - 6379
    volumes:
      - redis:/data
    labels:
      com.datadoghq.ad.logs: '[{"source": "redis", "service": "redis"}]'
      com.datadoghq.ad.check_names: '["redisdb"]'
      com.datadoghq.ad.init_configs: '[{}]'
      com.datadoghq.ad.instances: '[{"host":"%%host%%","port":"6379","command_stats":true}]'
    environment:
      - DD_SERVICE
      - DD_ENV
      - DD_VERSION

  datadog:
    container_name: datadog
    image: "datadog/agent:7.41.0"
    environment:
      - DD_API_KEY
      - DD_TAGS
      - DD_ENV
      - DD_SITE
      - DD_APM_ENABLE=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true
      - DD_LOGS_CONFIG_AUTO_MULTI_LINE_DETECTION=true
#      - DD_AC_EXCLUDE=name:datadog
      - DD_LOG_LEVEL=error
    expose:
      - 8126
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - ./datadog/run:/opt/datadog-agent/run:rw
    labels:
      com.datadoghq.ad.logs: '[{"source": "datadog-agent", "service": "datadog"}]'


  synthetics:
    container_name: synthetics
    image: "datadog/synthetics-private-location-worker"
    platform: linux/amd64 # no docker image for arm64 yet
    environment:
      - DATADOG_API_KEY=$DD_API_KEY
      - DATADOG_ACCESS_KEY
      - DATADOG_SECRET_ACCESS_KEY
      - DATADOG_PUBLIC_KEY_PEM 
      - DATADOG_PRIVATE_KEY
      - DATADOG_SITE=$DD_SITE
    labels:
      com.datadoghq.ad.logs: '[{"source": "synthetics", "service": "synthetics"}]'



volumes:
  redis:
    driver: local
