services:

  terraform:
    build: ./build/.
    environment:
      - TERM=xterm-256color
    container_name: box
    volumes:
      - ./entrypoint.sh:/opt/box/entrypoint.sh # entrypoint
      - ./conf:/opt/box/terraform # terraform configuration
      - home:/home/ubuntu

volumes:
  home:
    driver: local
